# -*- coding: utf-8 -*-
"""TopRatedTVshows.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixZv9xhh0JvF9aJyIODAq8cPclVUNyKK
"""

import numpy as np
import requests as r
import pandas as pd

response=r.get("https://api.themoviedb.org/3/discover/tv?api_key=ab9c6cb13f050b38772655608f40bd53&include_adult=false&language=en-US&page=1&sort_by=vote_average.desc&vote_count.gte=200")

pd.DataFrame(response.json()['results'])[['id','name','first_air_date','overview','popularity','vote_average','vote_count']]

df=pd.DataFrame()

for i in range(1,106):
  response=r.get("https://api.themoviedb.org/3/discover/tv?api_key=ab9c6cb13f050b38772655608f40bd53&include_adult=false&language=en-US&page={}&sort_by=vote_average.desc&vote_count.gte=200".format(i))
  temp_df=pd.DataFrame(response.json()['results'])[['id','name','first_air_date','overview','popularity','vote_average','vote_count']]
  df=pd.concat([df, temp_df], ignore_index=True)

df

df.to_csv('tvshows.csv')